moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.14.0
project:
  name: gx10-install
  mode: personal
  description: ''
  created_at: '2026-02-01 19:35:25'
  template_version: 1.14.0
  optimized: false
